### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by lstsystems** [dawehner/menu_per_role#1]
I'm having this error every time i assign a menu to a user role.

Notice: Undefined index: weight in Drupal\Core\Entity\Entity\EntityFormDisplay->processForm() (line 205 of C:\inetpub\wwwroot\dru8\core\lib\Drupal\Core\Entity\Entity\EntityFormDisplay.php).

**Comment by FlorentTorregrosa** [comment]
Pull request done that should fix the issue.

**Comment by dawehner** [comment]
@FlorentTorregrosa do you want to be committer on this project? Anyway, the PR is merged now
