### ISSUE TITLE
Menu is gone from the menu

### ISSUE THREAD

**Issue by heshanlk** [dawehner/menu_per_role#3]
When I choose the menu link only to show for the anonymous users, the menu link is completely gone from the menu management interface so I no longer edit the menu.

**Comment by FlorentTorregrosa** [comment]
@heshanlk: You must configure admin per role to allow menu per role administrators to see the every links.

**Comment by heshanlk** [comment]
I assume you mean admin per menu?

**Comment by FlorentTorregrosa** [comment]
The menu_per_role module provides a permission "Administer menu per role".

Yes I wrote too fast in my previous comment, instead of "admin per role" it was "menu per role"

**Comment by heshanlk** [comment]
Thanks
